name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # --- DÉBUT DES AJOUTS ---
      - name: Create local.properties
        run: |
          echo "sdk.dir=${{ runner.tool_cache }}/android/sdk" > "$GITHUB_WORKSPACE/android/local.properties"
        # OU alternativement, si le runner.tool_cache ne fonctionne pas toujours
        # echo "sdk.dir=/usr/local/lib/android/sdk" > "$GITHUB_WORKSPACE/android/local.properties"
        # Expliquons ici que $GITHUB_WORKSPACE est la racine du dépôt,
        # et que le fichier doit être créé dans android/
      # --- FIN DES AJOUTS ---

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./android

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace --info
        working-directory: ./android
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/app/my-release-key.jks
          KEYSTORE_PASSWORD: votre_mot_de_passe_keystore
          KEY_ALIAS: votre_alias_de_cle
          KEY_PASSWORD: votre_mot_de_passe_cle

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
