name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew # MODIFIÉ ICI : ajout de ./android/

      - name: Build release APK
        run: ./android/gradlew assembleRelease # MODIFIÉ ICI : ajout de ./android/
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/app/my-release-key.jks
          KEYSTORE_PASSWORD: votre_mot_de_passe_keystore
          KEY_ALIAS: votre_alias_de_cle
          KEY_PASSWORD: votre_mot_de_passe_cle

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
