name: Android CI

on:
  push:
    branches:
      - main # Ou la branche que vous utilisez pour les versions de release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease
        env:
          # Remplacez ces valeurs par celles de votre keystore.
          # Ceci est pour un test simple, ce n'est PAS sécurisé pour la production.
          KEYSTORE_PATH: ${{ github.workspace }}/app/my-release-key.jks # Chemin vers votre fichier .jks
          KEYSTORE_PASSWORD: votre_mot_de_passe_keystore # Remplacez par le vrai mot de passe
          KEY_ALIAS: votre_alias_de_cle # Remplacez par votre vrai alias
          KEY_PASSWORD: votre_mot_de_passe_cle # Remplacez par le vrai mot de passe

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk # Assurez-vous que le chemin est correct
