name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # L'étape chmod doit aussi être exécutée depuis le bon répertoire
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # gradlew est à la racine du sous-dossier 'android'
        working-directory: ./android # <-- AJOUTÉ ICI : Exécute cette commande dans le dossier android/

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace --info # Gardons les options de débogage pour l'instant
        working-directory: ./android # <-- AJOUTÉ ICI : Exécute cette commande dans le dossier android/
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/app/my-release-key.jks
          KEYSTORE_PASSWORD: votre_mot_de_passe_keystore
          KEY_ALIAS: votre_alias_de_cle
          KEY_PASSWORD: votre_mot_de_passe_cle

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          # Le chemin est relatif à la racine du dépôt, donc 'app/build...' est correct ici
          path: android/app/build/outputs/apk/release/app-release.apk # <-- VÉRIFIEZ CE CHEMIN. Il devrait être 'android/app/build...' si 'app' est un sous-dossier de 'android'
