name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java Development Kit
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.2' # Version de Flutter épinglée

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: ./ 

      - name: Verify package_config.json exists
        run: test -f ./.dart_tool/package_config.json || true # Commande modifiée pour vérifier l'existence du fichier
        working-directory: ./ 
      
      - name: Create local.properties for Android SDK and Flutter SDK paths
        run: |
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties
        working-directory: ./ 

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
        working-directory: ./android

      # - name: Decode Keystore # ÉTAPE COMMENTÉE
      #   run: |
      #     echo "Attempting to decode keystore..."
      #     if [ -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
      #       echo "KEYSTORE_BASE64 secret is not set or is empty."
      #       exit 1
      #     fi
      #     mkdir -p android/app # Ensure the directory exists
      #     echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-keystore.jks
      #     if [ $? -ne 0 ]; then
      #       echo "Failed to decode keystore."
      #       exit 1
      #     fi
      #     if [ ! -s android/app/release-keystore.jks ]; then
      #       echo "Decoded keystore file is empty. Check base64 encoding or secret."
      #       exit 1
      #     fi
      #     echo "Keystore decoded successfully to android/app/release-keystore.jks"
      #   working-directory: ./ 

      - name: Build Android Debug APK # Nom de l'étape mis à jour
        run: ./gradlew assembleDebug --stacktrace --info # Commande changée pour assembleDebug
        working-directory: ./android
        # La section env pour la signature a été supprimée car non requise pour assembleDebug
